In [1]:
from dataExtraction_andCkeaning import read_whatsapp_chat
from pathlib import Path
import warnings
warnings.filterwarnings("ignore")

data_directory = Path("data")

all_chat = read_whatsapp_chat(data_directory)

all_chat.head(20)

Found 3 zip file(s): ['WhatsApp Chat with Gomycode Instructors👨🏽_💻.zip', 'WhatsApp Chat with Xmeon 2015❤️✈️.zip', 'WhatsApp Chat with ⚽Football-talk⚽.zip']

  ✓ WhatsApp Chat with Gomycode Instructors👨🏽_💻.zip: 144,318 characters loaded
  ✓ WhatsApp Chat with Xmeon 2015❤️✈️.zip: 502,777 characters loaded
  ✓ WhatsApp Chat with ⚽Football-talk⚽.zip: 679,444 characters loaded

Total characters across all chats: 1,326,542
Total messages parsed: 9,082

,timestamp,sender,message
0,2024-04-06 11:50:00,+234 816 789 0224,"hello everyone, please i need to fill urgently..."
1,2024-04-06 15:16:00,Temitayo Gomycode,"Hello Team, Please concerning the slack invita..."
2,2024-04-06 15:17:00,Temitayo Gomycode,Please kindly remind all your students from Ma...
3,2024-11-06 10:40:00,Temitayo Gomycode,"Hello Everyone,\nI hope your day is going on s..."
4,2024-06-16 15:57:00,+234 701 843 8618,Eid Mubarak to our Muslim instructors. Have a ...
5,2024-06-21 03:28:00,Temitayo Gomycode,"Hello, everyone.\nPlease, for those who haven'..."
6,2024-06-21 07:47:00,+234 811 494 6485,"Good morning ma, noted"
7,2024-01-07 13:29:00,Temitayo Gomycode,"Hello Instructors,\nHappy new month.\nI hope y..."
8,2024-04-07 14:20:00,Temitayo Gomycode,"*DEMO DAY*\nHello Instructors,\nI hope your da..."
9,2024-04-07 14:47:00,+234 803 475 2345,It'll be a challenge...\nMost Part time studen...
10,2024-04-07 15:06:00,Temitayo Gomycode,We have always had our Demo Day Events on Frid...
11,2024-04-07 15:06:00,+234 803 475 2345,Alright
12,2024-05-07 10:11:00,Temitayo Gomycode,"*INSTRUCTOR'S MEET-UP*\nHello All,\nI hope you..."
13,2024-05-07 10:32:00,+234 906 494 2385,It says i need permission
14,2024-05-07 11:43:00,Temitayo Gomycode,Please check now
15,2024-05-07 13:39:00,Temitayo Gomycode,*INCREASED NUMBER OF DAMAGED CHAIRS*\nHello In...
16,2024-05-07 21:27:00,Philip Digital Marketing,Thank you for the information @⁨Temitayo Gomyc...
17,2024-06-07 07:47:00,+234 701 843 8618,"Nice, we will check it out and give you feedba..."
18,2024-06-07 07:49:00,+234 701 843 8618,"It's Fried rice and Chicken me I want😂, I don'..."
19,2024-06-07 07:50:00,+234 701 843 8618,Forwarded to all the culprits(students) I know😌.

In [2]:
all_chat = all_chat.iloc[1:, :]
all_chat.head()

,timestamp,sender,message
1,2024-04-06 15:16:00,Temitayo Gomycode,"Hello Team, Please concerning the slack invita..."
2,2024-04-06 15:17:00,Temitayo Gomycode,Please kindly remind all your students from Ma...
3,2024-11-06 10:40:00,Temitayo Gomycode,"Hello Everyone,\nI hope your day is going on s..."
4,2024-06-16 15:57:00,+234 701 843 8618,Eid Mubarak to our Muslim instructors. Have a ...
5,2024-06-21 03:28:00,Temitayo Gomycode,"Hello, everyone.\nPlease, for those who haven'..."

#### Text Sequence

The text shpuld be merged into a single sequence to prepare it for the next step, where the BPE algorithm will be applied and the text will be encoded

In [3]:
def prepare_corpus(df, save_path="combined_text.txt"):
    cleaned_messages = (
        df["message"]
        .dropna()
        .str.replace("\\n", " ", regex=False)
        .str.replace("\n", " ", regex=False)
        .str.replace(r'\s+', ' ', regex=True)
        .str.strip()
    )

    whatsapp_corpus = "\n".join(cleaned_messages.tolist())

    print(f"WhatsApp characters : {len(whatsapp_corpus):,}")

    with open(save_path, "w", encoding="utf-8") as f:
        f.write(whatsapp_corpus)

    print(f"Saved to: {save_path}")

    return whatsapp_corpus


corpus = prepare_corpus(all_chat)

WhatsApp characters : 682,464
Saved to: combined_text.txt

In [4]:
corpus

'Hello Team, Please concerning the slack invitations, The support team just confirmed that it was only sent to the May session students and those after. So for those that didn\'t receive, its because your session started before May.\nPlease kindly remind all your students from May session to please accept the invitation.\nHello Everyone, I hope your day is going on smoothly. This is to inform you all that we would be observing the June Holiday tomorrow. Classes will resume on Thursdy the th of June, . Please note that the Hackerspace will be locked on Wednesday. Also, to mark the Muslim Holidays coming up on the th and th of June, , We will be closing on Monday and Tuesday the th and th of June, . The Hackerspace will also be locked during this period. All classes will resume back on Wednesday, the th of June, . Please note that all classes for this Saturday the th of June, will hold. Thank you GOMYCODE\nEid Mubarak to our Muslim instructors. Have a blast.\nHello, everyone. Please, for those who haven\'t sent their invoices yet, please remember to do so for May-June at the latest today. Thank you\nGood morning ma, noted\nHello Instructors, Happy new month. I hope your day is going well. This is an update about the salary for June. We are experiencing a lot of errors with the payment slips. There is a new rule that there will no longer be payment exceptions from the month of July. This implies that if your makeup or extra class is not captured on the rescheduled platform, payment won\'t be captured. So it\'s important to send an email at least days before an extra class is scheduled. We are thereby trying to make sure that all errors are addressed. We are working on this at the moment. Payments will be made by tomorrow. Kindly exercise some patience. Thank you.\n*DEMO DAY* Hello Instructors, I hope your day is going well. This is to notify you about our upcoming Demo Day event. The Event will be happening on Friday, the th of July, . ( weeks from now). As we always do, I\'d like you to please send me a list of students who have exceptional projects so they can present. These students are also expected to come to the hackerspace to present to the management before the Event. Please, kindly send in your students\' names by the close of business tomorrow at most. This is to help us plan adequately. This applies to both FT and PT Instructors and Students. Thank you.\nIt\'ll be a challenge... Most Part time students chose part time because they usually don\'t have time during the weekdays... Having their demo on a weekday is already guaranteed to yield low participation.\nWe have always had our Demo Day Events on Fridays Historically. So we\'ld work with those available\nAlright\n*INSTRUCTOR\'S MEET-UP* Hello All, I hope your day is starting well. This is to announce our Instructor\'s meeting date for the second part of the year. The event will be next Friday, the th of July, . It is an Event for all FT and PT instructors. Kindly fill out the Google form below to enable us to plan refreshments according to the attendance. Please note that the event is a very important one. All questions and pending inquiries will be addressed. Also, latest updates will be shared to keep us all abreast with the organization\'s plans and goals. It would also be a time to catch up and network with other instructors and have a get-together event as well. We urge all instructors to please plan to attend. Thank you.\nIt says i need permission\nPlease check now\n*INCREASED NUMBER OF DAMAGED CHAIRS* Hello Instructors, It has come to our notice that students are continuously damaging our chairs and the instructors do not report the incident. They destroy the chairs and complain to us that the chairs are bad. You need to let these students know that henceforth if they damage our chairs, they will be held responsible. Please communicate with your students on all platforms. Going forward, the instructors should take the responsibility of correcting them when they slouch on the chairs or sit carelessly. Please flag all cases of damages immediately. You all need to be concerned enough to protect company property and if the students are being recalcitrant, the instructors should call the attention of the HSM to the situation. And I will take this up. Please kindly treat this as urgent. Thank you.\nThank you for the information @\u2068Temitayo Gomycode\u2069 Hi everyone, how are you doing? So excited to inform you about my new tech company Blurp Space 💃🏻🕺🏻 It is a multi vendor ecommerce site where you can upload your products for FREE as a Vendor or earn by selling other people\'s products from home or anywhere as an Affiliate.💸💵 If you are interested, here are my company’s social media handles: *Follow any one that connects to you more.👇🏾 Click, like, follow, subscribe to any or all the socials, depending on which one you use frequently.❤️❤️ *(If you are interested, please feel free to ask all the questions you have in mind in the comment section and retweet or reshare to anyone you feel this might help)*\nNice, we will check it out and give you feedback. Kudos and keep pushing.💯\nIt\'s Fried rice and Chicken me I want😂, I don\'t want to network 🫣😂😂.\nForwarded to all the culprits(students) I know😌.\nThank Daniel\nReally do appreciate it\nGood morning all, Concerning the Instructor\'s meet-up coming up this Friday, so far only people have registered. Please register if you know you haven\'t done so. Registration is important for attendance. Thank you\nHello All, I hope your day is going well. I\'m yet to receive the names of your graduated students ready to present their projects for Demo Day. Please kindly send in the names of your students by the latest tomorrow. Thank you.\nHello Everyone, I hope your day is going well. This is a final message about registering for the instructors meet-up event. Like earlier explained, the number of registered instructors will help with planning. It is an important event for all instructors and registeration is important for attendance. I can only cater for those who register. Also, according to the polls, more instructors are comfortable with noon than pm. Therefore, the event will be for noon on Friday. Its for hours maximum. Kindly prepare to attend. Thank you.\nHello Instructors, Here is a quick reminder about our meet up event today at noon Please plan yo arrive early. And please confirm your availability with me in a private chat again this morning. Thank you.\nOnly people have confirmed availability. Please kindly confirm to help us plan properly\nDone\nMy apologies for my late response. I was only able to reschedule my meeting this morning\nSteps to clear cache: . Right-click anywhere on the platform . Click the last option "Inspect" . A window will open to the right, click on the " >>" button, you\'ll see a drop down, then click on Applications. . Scroll down to clear site data. . Click on Ctrl + Shift +R to refresh.\nlearn.gomycode.co\nHello All. I hope your day is going well. Please be reminded to always mark your attendance hrs into your classes. Aside from missing your pay for unmarked classes, you are always flagged weekly when you miss your attendance, Please it doesn\'t take anything to mark your attendance. Please always prioritize this. Thank you\nHello All, Please Send your Demo-Day-Presenting Students to come and present for selection latest tomorrow. Please kindly treat as urgent\nHi good afternoon all, 😊. Will the newly adjusted minimum wage affect GMC as it will to other private firms as Stated by the organized private sector labour. How will it be implemented? And when? @\u2068Temitayo Gomycode\u2069 pls don’t air me😓\n👍Seconded 😀\nHello All. I hope your day is going well. Please send in your invoice for June st-July th. We are behind time already. Please treat as urgent. Thank you\nNoted.\nHello All, I hope your day is going well. Please encourage your students to come for the Demo Day Event this Friday. I know most of them are off on Fridays but please encourage them to see the importance of attending to prepare them ahead for their own turn. I count on you to push this. At least for those not working full time. Thank you.\nWhat time will it be starting?\npm to pm\n👍\nHello All, I hope your day is going well. The UX/UI Designers on our Central Team are currently conducting research on a new feature we are developing. We need you to please share the link below with your students to help us with their feedback. I count on you to please push this. Thank you.\nOkay, will do\nGood evening\nHello All, I hope your day is going well. This information is concerning the proposed Protest slated to take place on Thursday, the st of August. To be safe, all classes for Thursday will be held online, as the Hackerspace will be closed for Safety. If by Friday there are no protests, all classes will resume back by the weekend. Please kindly take note and help inform your students. We have also shared the information on their Telegram group. We count on you to help get this across. Let\'s all be safe. Thank you.\nWe pray for peace. Thank you for taking this safety measure\nAmen\nHello All, I hope your day is going well and we are all keeping safe. Please for those expected to have classes online today (FT), kindly send me a screenshot of your classes held online and mark your attendance. Please treat as urgent\nGood morning Temitayo... Any info on the weekend classes??\nHello Ikenna, We will communicate at or before the close of business today. In the meantime, there is no decision regarding that yet.\nOkay\nHello All, I hope your day is going well. This is an update concerning the ongoing Nationwide Protest. *To be safe, all PT classes for this weekend (Saturday and Sunday) will be held online, as the Hackerspace will be closed for Safety*. *Please all instructors should create a meeting link and share it with me and all your students*. *A screenshot should also be taken to capture attendance and share with me*. The link and screenshots will determine if attendance will be marked as a successful class. Please encourage your students to attend as the class will not be replaced if they don\'t turn up. All new sessions for this weekend have been moved up to next weekend, the th of August, . All instructors to take the new sessions, please take note. Please assist in informing your students via your various groups. We have also shared the information on their Telegram group. We count on you to help get this across. Let\'s all be safe. Thank you.\nThank you very much for the update @\u2068Temitayo Gomycode\u2069. I think having the classes online may be very challenging due to bad internet network service lately. I don’t know if this is peculiar to my area or it’s a general issue .\nIt\'s general\nMy students already pointed this out\nThis is noted. Please, if you attempt to have your class and it doesn\'t work within the first hour, please notify me so we can reschedule the class. But please do not mark the attendance for such class. Thank you.\nIn addition to this concern, I am not sure of a service that provides up to hours of free Video call meeting time.\nMultiple links would work for this...\nHello Triumph, Use Google Meet. And As Ikenna mentioned. Try that too\nGood morning All. Only instructors ha e shared their links with me. Please create your links with me and your students as well. Please treat as Urgent\nI will, these has been noted.\nOkay will do\nGood Afternoon\nAll done\nPlease All, kindly confirm if your network situation was/is good enough for your classes?\nConfirmed\nmy network is active\nI have forwarded a screenshot via email to you.\nNot bad though a couple of student have it worse\nHi Temitayo, students are complaining about the network\nI dont think it is a network issue because my network is crystal clear and some other students joined in\nThe students complaining are those who are in noisy environments, and I just spoke to them to find somewhere quiet\nA lot of people generally are experiencing network issues and this has been the case since Thursday. If your attendance is less than %, you may need to reschedule\nGood All, Please kindly note that the hackerspace will be open for classes tomorrow since the virtual classes didn\'t work today because of the bad Internet. Besides, I noticed there were vehicular movements in Yaba today. So please, for those that have classes tomorrow, the hackerspace will be open. Thank you.\nAll new sessions are still resuming next week\nPlease let\'s help to inform our students so they can come in tomorrow. Thank you.\n@\u2068~Daniandre\u2069 She said to inform the students that class will resume tomorrow. 👍🏾✅\nI think this was meant for Sunday\'s class. But thanks still...\nHello All, For clarity, classes are to resume physically tomorrow .\nGood Afternoon All, And Happy Sunday. Its important that all instructors should be onboarded on Slack. This helps you report issues faster and more reliably. The following instructors should please confirm if you have logged into slack successfully. Please kindly treat as urgent: Yakub Ibrahim Adam Veronica Peter Triumphant Adiga Taofeek Olawoye Stephen Akintola Saviour John Samuel Momoh Philip Owoju Oluwafemi Adeleye Olukayode Ogunnaike Olatunde Jaiyeola Olabode Oduwole OJIAKU DANIEL DANIEL ARINZE NA OJIAKU DANIEL ARINZE NA FT Obinna Oliseneku Micheal Olomu Kingsley Ifeanyi Kehinde Oyedepo Jacob Ojumu Israel Iroegbu Ikenna Enyidede Husseini Mudi Husseini Mudi Funto Oladipupo Babatunde Olanrewaju Adams Bolaji Aaron Ugede Chukwuebuka Felix\nAdams Bolaji ✅\nGood Afternoon Samuel Momoh: Logged in successfully ✅\nKingsley Ifeanyi ✅\nAdiga Triumphant ✅\nGood afternoon, Olabode Oduwole ✅ Thank you.\nVeronica Peter✅\nObinna Oliseneku ✅\nAkintola Stephen ✅\nJacob Ojumu ✅\nMicheal Olomu ✅\nOlatunde Jaiyeola logged in ✅\nLogged in\nLogin in\nI have for the past weeks\nLogged in\nHello Dele, trust your family is doing fine. My organisation is currently recruiting for a Full-Stack Developer. Can you recommend a candidate looking for a job in this line? Based in Abuja, Male or Female\nHello everyone. Please recommend via dm\nSaviour John ✅\nGood morning, All. I hope your day is starting well. Please, I am in need of Artificial intelligence and Generative Ai instructors. (The difference is that the latter is a tool/app based engineer). I also need Tech for business, ISTQB and Unity Game instructors. Please send me a referral if you know anyone. Thank you.\nHello All. I hope your day is going well. Please send in your invoice for June st-July th, today. Please treat this as urgent. Thank you\nGood Morning Temitayo Sent\nSpread the good news. This is our students startup 👍\nNice\nGood afternoon, please who does IAM?\nHello All, I hope your day is going well. Please inform your students to join the Slack channel. Especially the new ones. Please treat as urgent. Thank you.\nNoted\nHello everyone, please I need recommendations for a good cybersecurity instructor in Ikeja hackerspace...thank you 🙏🏽\n*DEMO DAY EVENT SEPTEMBER* Hello Everyone, I hope your day is going well. This is to notify you about our upcoming Demo Day event. The Event will be happening on Friday, the th of September, . (About weeks from now). As we always do, I\'d like you to please send me a list of students who have exceptional projects so they can present. These students are also expected to come to the hackerspace to present to the management before the Event. Please, kindly send in your students\' names by the close of business tomorrow at most. This is to help us plan adequately. This applies to both FT and PT Instructors and Students. Thank you.\n*FUN DAY EVENT SEPTEMBER* Hello Everyone, I hope your day is going well. This is to announce our Funday/ Social Event coming up this Friday, the th of September, . The time for the event is noon to pm. We need students who can bring their PS or PS device. Please help communicate the event to your students and please reach out to me if there is any student who can borrow us a PS device for the event. We will have other fun events available at the space with light refreshment just to unwind and network with ourselves. Please help communicate with your students. Thank you.\nHello All, please share this Telegram link with your students that are yet to join. Thank you.\nDone\nBREAKING: FG declares Monday Eid-ul-Mawlid holiday @\u2068Temitayo Gomycode\u2069 any updates on this. Thank you\nHello Everyone, I hope your day is going on smoothly. This is to inform you all that we will be observing the Muslim Holiday on Monday, the th of September, . Classes will resume on Tuesday the th of September, . Just so you know, the Hackerspace will be locked on Monday. All classes for this Sunday the th of September, will be held. Thank you GOMYCODE\n*PANEL DISCUSSION EVENT SEPTEMBER* Hello Everyone, I hope your day is going well. This is to announce our event coming up on the st of September, . It is an Educative Panel Discussion Session tagged: AI and my career progression. We would have Panelists for top-tier companies come in to speak with us about this part of tech and how you can key into it. We encourage you all to attend and speak to your students about attending the event. We hope to see you there Gomycode\nWill do\nHello All. I hope your day is going well. Please send in your invoice for August st-September th, today. Please treat this as urgent. Thank you\nHello All, Please Im in need of someone who can take AI and Generative AI courses. Please send me referrals privately. Thank you\nHello everyone. Please I need recommendations for someone available for Intro to Web (html, css, JavaScript) in Ikeja HS, Sunday -pm. It’s kinda urgent to start next month🙏🏽\nHello All, Please prepare your students presenting for Demo day for this Friday. Please tell them to come for screening between Moday and Tuesday, We are a bit behind the time. Please treat as urgent. Thank you\nHello All, I hope tour day is starting right. Please here is a reminder to send in your students to present their projects for Demo day coming up this Friday. Also, please inform them about the Generative AI event happening on Saturday. We will be having external speakers at the hackerspace. Please encourage them to attend. Thank you.\nHello All, Good morning. Please help invite your students for the Generative AI event holding this Saturday at pm. We are inviting speakers and we need the turn out to be encouraging. Please share the link for them to register: Generative AI Event LInk (Saturday th of September): The link to register for Demo Day (Friday, the th of September) : Thanks\nHello Everyone, I hope your day is going on smoothly. This is to inform you all that we will be observing the Independence Day Holiday tomorrow, the st of October, . Classes will resume on Wednesday the nd of October, . Just so you know, the Hackerspace will be locked tomorrow. Thank you GOMYCODE\n*DEMO DAY* Hello Instructors, I hope your day is going well. This is to notify you about our upcoming Demo Day event. The Event will be happening on Friday, the th of October, . ( days from now). As we always do, I\'d like you to please send me a list of students who have exceptional projects so they can present. These students are also expected to come to the hackerspace to present to the management before the Event. Please, kindly send in your students\' names by the close of business tomorrow at most. This is to help us plan adequately. This applies to both FT and PT Instructors and Students. Thank you.\nHello All, Good morning. I\'m yet to get the names of the students presenting for Demo Day from you all. Please kindly treat this as urgent today. We only have one more week to the event. Thank you.\nGood morning everyone. Please I need recommendations for a fulltime data science instructor for our Ikeja HS. Thank you very much in anticipation 🙏🏽\nHello All, Good morning. I\'m yet to receiv